version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: php_container
    volumes:
      - ./index.php:/var/www/html/index.php
    ports:
      - "8888:80"
    depends_on:
      - db
    command: bash -c "docker-php-ext-install pdo_mysql && apache2-foreground"

  db:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: meineDatenbank

    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
